port: 587 # For starttls
host: smtp.gmail.com
sender: mkapp.server@gmail.com
password: Diplomovapraca123
confirm_subject:
  subject: Confirmation of registration
delete_subject:
  subject: Deactivation of account

# subject: Confirmation of registration
confirm:
  message: "<h1>Your accout was confirmed! Now, you can log in </h1>"
cancel:
  message: "<h1>Your accout was deactivated</h1>"
